// Plan configuration - which features each plan has access to
export const planFeatures: Record<string, string[]> = {
  free: [
    'plans',
    'downloads',
    'settings',
  ],
  basico: [
    'plans',
    'downloads',
    'instances',
    'jarvis',
    'commands',
    'triggers',
    'reports',
    'settings',
  ],
  mensal: [
    'plans',
    'downloads',
    'instances',
    'jarvis',
    'commands',
    'triggers',
    'chatbot',
    'reports',
    'announcements',
    'campaigns',
    'auto-group',
    'auto-private',
    'settings',
  ],
  trimestral: [
    'plans',
    'downloads',
    'instances',
    'jarvis',
    'commands',
    'triggers',
    'chatbot',
    'leads',
    'reports',
    'announcements',
    'campaigns',
    'auto-group',
    'auto-private',
    'pix',
    'settings',
  ],
  anual: [
    'plans',
    'downloads',
    'instances',
    'jarvis',
    'commands',
    'triggers',
    'chatbot',
    'leads',
    'reports',
    'announcements',
    'campaigns',
    'auto-group',
    'auto-private',
    'pix',
    'settings',
  ],
  vitalicio: [
    'plans',
    'downloads',
    'instances',
    'jarvis',
    'commands',
    'triggers',
    'chatbot',
    'leads',
    'reports',
    'announcements',
    'campaigns',
    'auto-group',
    'auto-private',
    'pix',
    'settings',
  ],
  master: [
    'plans',
    'downloads',
    'instances',
    'jarvis',
    'commands',
    'triggers',
    'chatbot',
    'leads',
    'reports',
    'announcements',
    'campaigns',
    'auto-group',
    'auto-private',
    'pix',
    'settings',
  ],
};

export const planNames: Record<string, string> = {
  free: 'Free',
  basico: 'Básico',
  mensal: 'Mensal',
  trimestral: 'Trimestral',
  anual: 'Anual',
  vitalicio: 'Vitalício',
  master: 'Master',
};

export const getAvailableFeatures = (plan: string): string[] => {
  return planFeatures[plan] || planFeatures.free;
};
