#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# DEEP-AUREA - Pré-Deploy (Instruções)
# ═══════════════════════════════════════════════════════════════
# 
# Este script APENAS mostra as instruções.
# NÃO executa nada.
#
# ═══════════════════════════════════════════════════════════════

clear

echo "═══════════════════════════════════════════════════════════════"
echo "                                                                 "
echo "   DEEP-AUREA - Guia de Deploy na Hostinger VPS                "
echo "                                                                 "
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  PARTE 1: PREPARAÇÃO (faça no computador)"
echo "  ─────────────────────────────────────────"
echo ""
echo "  1. Acesse: https://hostinger.com.br/vps"
echo "  2. Compre o plano VPS KVM 2 (~R$35/mês)"
echo "  3. Escolha Ubuntu 22.04"
echo "  4. Anote: IP, senha e porta SSH"
echo ""
echo "  5. Acesse: https://hpanel.hostinger.com"
echo "  6. Vá em Domínios → DNS Zone Editor"
echo "  7. Adicione registro A:"
echo "     - Tipo: A"
echo "     - Nome: @"
echo "     - Valor: SEU_IP"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  PARTE 2: CONEXÃO (faça no computador)"
echo "  ──────────────────────────────────────"
echo ""
echo "  1. Abra o PowerShell"
echo "  2. Conecte ao VPS:"
echo ""
echo "     ssh root@SEU_IP"
echo ""
echo "  3. Digite a senha quando solicitado"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  PARTE 3: INSTALAÇÃO (faça no VPS)"
echo "  ─────────────────────────────────"
echo ""
echo "  Cole estes comandos NO TERMINAL do VPS:"
echo ""
echo "  # 1. Atualizar sistema"
echo "  apt update && apt upgrade -y"
echo ""
echo "  # 2. Instalar Docker"
echo "  curl -fsSL https://get.docker.com | sh"
echo ""
echo "  # 3. Instalar Docker Compose"
echo "  apt install docker-compose -y"
echo ""
echo "  # 4. Instalar NGINX"
echo "  apt install nginx -y"
echo ""
echo "  # 5. Instalar Git"
echo "  apt install git -y"
echo ""
echo "  # 6. Instalar Certbot (SSL)"
echo "  apt install certbot python3-certbot-nginx -y"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  PARTE 4: DEPLOY (faça no VPS)"
echo "  ────────────────────────────"
echo ""
echo "  # 1. Baixar o projeto"
echo "  git clone https://github.com/wwbcinformatica-gif/deep-aurea.git"
echo "  cd deep-aurea"
echo ""
echo "  # 2. Configurar chaves de API"
echo "  cp backend/.env.example backend/.env"
echo "  nano backend/.env"
echo "  (edite e salve com Ctrl+X, Y, Enter)"
echo ""
echo "  # 3. Iniciar"
echo "  docker-compose up -d --build"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  PARTE 5: NGINX (faça no VPS)"
echo "  ───────────────────────────"
echo ""
echo "  # 1. Criar configuração"
echo "  nano /etc/nginx/sites-available/deep-aurea"
echo ""
echo "  (cole o conteúdo do arquivo nginx-config.txt)"
echo ""
echo "  # 2. Ativar site"
echo "  ln -s /etc/nginx/sites-available/deep-aurea /etc/nginx/sites-enabled/"
echo "  rm /etc/nginx/sites-enabled/default"
echo ""
echo "  # 3. Testar e reiniciar"
echo "  nginx -t"
echo "  systemctl restart nginx"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  PARTE 6: SSL (faça no VPS)"
echo "  ─────────────────────────"
echo ""
echo "  # 1. Instalar certificado"
echo "  certbot certonly --standalone -d SEU_DOMINIO -d www.SEU_DOMINIO"
echo ""
echo "  # 2. Reiniciar NGINX"
echo "  systemctl restart nginx"
echo ""
echo "  # 3. Configurar renovação automática"
echo '  echo "0 0,12 * * * certbot renew --quiet" | crontab -'
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  PARTE 7: TESTAR!"
echo "  ────────────────"
echo ""
echo "  1. Abra o navegador"
echo "  2. Acesse: https://SEU_DOMINIO"
echo "  3. Você deve ver a tela de login"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  COMANDOS ÚTEIS:"
echo ""
echo "  Ver logs:          docker-compose logs -f"
echo "  Reiniciar:         docker-compose restart"
echo "  Parar:             docker-compose down"
echo "  Atualizar:         git pull && docker-compose up -d --build"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  CUSTOS:"
echo ""
echo "  VPS KVM 2:         ~R$35/mês"
echo "  Domínio:           ~R$40/ano"
echo "  SSL:               Grátis"
echo "  TOTAL:             ~R$38/mês"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
read -p "Pressione Enter para fechar..."
